### ISSUE TITLE
Local batou_ext in requirement.txt is turned into checkout in requirements.lock

### ISSUE THREAD

**Issue by icemac** [flyingcircusio/batou#104]
In a customer project I have a `batou_ext` package locally in the deployment repository. (***Caution:*** So we are not using the official https://github.com/flyingcircusio/batou_ext there but our own package which has the same name for historical reasons.)

`requirements.txt` contains:

```
...
-e ./batou_ext
...
```

After running `./batou appenv-update-lockfile` the `requirements.lock` contains something like:

```
...
-e git+ssh://git@DEPLOYMENT-REPOS-URL.git@8db844f7f49595bce32045d7afa92c38d70271fa#egg=batou_ext&subdirectory=batou_ext
...
```

This requires read access to that repository for all the machines I am deploying to. After changes in `./batou_ext` I have not only to commit and push them but also I have to run `./batou appenv-update-lockfile` so the changes are eventually used in the deployment.

Expectation: I'd like to see `-e ./batou_ext` in the `requirements.lock` file, too, as I always want to deploy the version of the utility package which is in the deployment repository at the time of the deployment. (That's why it is stored directly in the deployment repository not in a separate repository.)

**Comment by ctheune** [comment]
There are a few other instances of this. I guess we need to add some logic (and this is actually a bug for https://github.com/flyingcircusio/appenv) so that certain entries will be filtered out from the lock file and used literally from the requirements.txt) 

A way to do that could be:

* remove all '-e' entries from requirements.lock
* include all '-e' entries from requirements.txt

Trying to actually match names will likely be very brittle. We can add more cases like this based on a symmetric include/exclude filter.

**Comment by ctheune** [comment]
Ok, fixed in a newer appenv version:

https://github.com/flyingcircusio/appenv/commit/f26fbe0a669a681ff1c8ebd852d91a3cc6456017

**Comment by ctheune** [comment]
I've also added a note about how to upgrade appenv:

https://github.com/flyingcircusio/batou/commit/88bc238ad4e0ed2f16b77e7af57f9f4ad5b9916a
