### ISSUE TITLE
Deployment hangs on `Loading secrets ...`

### ISSUE THREAD

**Issue by jugmac00** [flyingcircusio/batou#19]
... if secrets file is opened in some other terminal.

**Reproduce**
`batou v1.12.0`

terminal one: `./batou secrets edit some_env` 

terminal two: `./batou deploy some_env`

terminal output hangs at:
```
./batou deploy some_env
Installing git+git://github.com/flyingcircusio/batou_ext.git@5f658851cfa521c5b439e54e398a719004707775#egg=batou_ext
batou/1.12.0 (CPython 2.7.15-candidate1, Linux 4.15.0-1064-oem x86_64)
================================================================ Preparing =================================================================
main: Loading environment `some_env`...
main: Verifying repository ...
     You are using rsync. This is a non-verifying repository -- continuing on your own risk!
main: Loading secrets ...
```

**expected (wished) behavior**
show some message like `Deployment cannot proceed as secrets file is currently in use. Please close it. Deployment will resume automatically.`

On the plus side... deployment already continues when you close the secrets file.

**Comment by ctheune** [comment]
<img width="538" alt="Screenshot 2020-05-11 at 15 38 08" src="https://user-images.githubusercontent.com/1220572/81567994-7036a780-939d-11ea-9e1f-23bc8a54249b.png">

Aaaand there you got. The current behaviour was not intentional and I'm more than happy to switch it over to a non-blocking version. Note that deployments do not hold the lock for a long time, but I think you don't want to run a deployment while still having an editor open (and as we keep the lock and the unencrypted file in a safe space the regular safety repository belts don't catch this) but you can start editing it after the deployment loaded the secrets initially.

**Comment by jugmac00** [comment]
master means `batou2`? (which would be totally fine)

**Comment by ctheune** [comment]
Yeah :)
