### ISSUE TITLE
Debugging batou?

### ISSUE THREAD

**Issue by icemac** [flyingcircusio/batou#199]
To debug issues in `batou` I am nowadays using [remote-pdb](https://pypi.org/project/remote-pdb/). It allows to start a debugger at any point in the code as it opens a remote port where the debugger can be accessed via `nc` or `telnet`.

To be able to use it in the tests I added `remote-pdb` locally to `tox.ini` as a dependency.

Would it be a good idea to add it (or another remote debugger) there permanently? (It does not hurt and eases debugging end to end tests.)
I can live with being forced to have to add the debugger to `requirements.txt` to debug actual `batou` runs.

**Comment by ctheune** [comment]
This is interesting. Can we look at this together and you show me how you work with it at the moment?

**Comment by ctheune** [comment]
I'd like to use this as a builtin-feature so that someone can add a simple breakpoint command (using py3 breakpoint()  magic) in their deployments that results in the port being opened and batou showing the relevant info on the console.

We could later think about an extended integration so that we directly connect stdin/out/err to the remote console, but not now.
