### ISSUE TITLE
Connecting with vagrant fails?

### ISSUE THREAD

**Issue by ctheune** [flyingcircusio/batou#53]
@sweh reported me this via chat:

```
default: Connecting via vagrant (1/1)
======================================================================================================================================= Configuring model ... =======================================================================================================================================
ERROR: Unexpected exception
      Traceback (most recent call last):
        File "/Users/sweh/dev/clxmci_deployment/.batou/2ed829d2e83a1c08d0384cba9b37cc22e8c3df118448c40b3b536e584923910e/lib/python3.6/site-packages/execnet/gateway_bootstrap.py", line 50, in bootstrap_exec
          assert s == "1".encode("ascii")
      AssertionError
```

**Comment by ctheune** [comment]
Using a current appenv and a batou 2.0b12 this works with no problem for me. We'll have to diagnose this together, I guess ...

**Comment by SoerenWeber** [comment]
This behavior was caused by the introduction of [`sudo`'s `-i` option](https://github.com/risclog-solution/batou/blob/57c1f0778e33d5a6a5891b83a684735dd3bbea03/src/batou/host.py#L171) on remote hosts and a `.profile` that generates some output. Execnet's guard subsequently failed because the expected output was prepended by the `.profile` output.

For now, I'm checking for an interactive shell (per `[[ $- == *i* ]]`) to suppress the output if it isn't needed. I don't yet see an obvious way to handle this situation in batou, though.

**Comment by ctheune** [comment]
Thanks for that hint. I'm closing this then.
